name: complete work
'on':
  push:
    branches:
    - main
jobs:
  complete:
    runs-on: ubuntu-latest
    steps:
      - uses: checkout@v3
      - name: node install
        uses: actions/setup-node@v4.1.0
      - name: npm install, build and test
        run: |
          npm i
          npm run build
          npm test
        shell: bash